const { OpenAI } = require("openai");

const openai = new OpenAI({
  apiKey: process.env.OPENROUTER_API_KEY || "",
  baseURL: "https://openrouter.ai/api/v1",
});

const searchTool = {
  type: "function",
  function: {
    name: "search_legal_data",
    description: "Searches the legal database.",
    parameters: {
      type: "object",
      properties: {
        q: { type: "string" },
      },
      required: ["q"]
    }
  }
};

async function run() {
  const messages = [
    { role: "user", content: "latest document regarding energy" }
  ];

  try {
    console.log("Step 1: First call to deepseek-v4-flash...");
    const res1 = await openai.chat.completions.create({
      model: "deepseek/deepseek-v4-flash",
      messages,
      tools: [searchTool],
      tool_choice: "auto"
    });

    const msg1 = res1.choices[0].message;
    console.log("First Response msg1:", JSON.stringify(msg1, null, 2));

    if (msg1.tool_calls && msg1.tool_calls.length > 0) {
      console.log("\nStep 2: Mocking tool execution...");
      const hits = [
        { id: "32024R1234", title: "Regulation on Energy Infrastructure", snippet: "Recent EU Energy regulation." }
      ];

      const updatedMessages = [
        ...messages,
        msg1,
        {
          role: "tool",
          tool_call_id: msg1.tool_calls[0].id,
          content: JSON.stringify(hits)
        }
      ];

      console.log("\nStep 3: Sending tool results back to deepseek-v4-flash...");
      console.log("Updated Messages for Step 3:", JSON.stringify(updatedMessages, null, 2));

      const res2 = await openai.chat.completions.create({
        model: "deepseek/deepseek-v4-flash",
        messages: updatedMessages
      });

      console.log("Final Response:", JSON.stringify(res2.choices[0].message, null, 2));
    } else {
      console.log("No tool calls generated by the model.");
    }
  } catch (err) {
    console.error("OpenRouter error:", err);
  }
}

run();
